# Generated by Django 6.1.1 on 2026-09-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='uploads/')),
                ('status', models.CharField(choices=[('signed', 'Signed'), ('unsigned', 'Unsigned')], default='unsigned', max_length=50)),
            ],
        ),
    ]
