# Generated by Django 6.1.1 on 2026-09-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_pdffile_alter_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='media/')),
                ('status', models.CharField(choices=[('signed', 'Signed'), ('unsigned', 'Unsigned')], default='unsigned', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
