# Generated by Django 6.1.1 on 2026-09-24 12:38

import django.core.validators
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_image_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='pdf',
            field=models.FileField(max_length=500, upload_to=documents.models.set_pdf_file_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
