# Generated by Django 6.1.1 on 2026-09-25 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_pdffile_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='status',
        ),
    ]
