# Generated by Django 6.1.1 on 2026-09-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_image_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to='images/'),
        ),
    ]
